name: flutterstore
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  intl: ^0.18.1
  logger: ^2.5.0
  url_launcher: ^6.1.11
  get_storage: ^2.1.1
  flutter_native_splash: ^2.2.18
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  carousel_slider: 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/banners/
    
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/icons/payment_methods/
    - assets/icons/categories/
    - assets/icons/categories/
    # - images/a_dot_burr.jpeg
  
    
    
         
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/urbanist/Urbanist-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
  #         weight: 800
                                                                                                                #   weight: 800
      

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
